// constants.js

const ADD_PERSON_REQUEST = 'ADD_PERSON_REQUEST';
const ADD_PERSON_SUCCESS = 'ADD_PERSON_SUCCESS';
const ADD_PERSON_ROLLBACK = 'ADD_PERSON_ROLLBACK';
const DELETE_PERSON = 'DELETE_PERSON';

export {
  ADD_PERSON_REQUEST,
  ADD_PERSON_SUCCESS,
  ADD_PERSON_ROLLBACK,
  DELETE_PERSON,
};
